### PR TITLE
Fix: Fast Reload not working on testnet mode

### LINKED ISSUE #493: Bug: Fast Reload not working on testnet mode
## Description
When interacting with `Debug Contract` on testnet mode, Fast Reload is not working 

Image

We are forced to click on the reload button to see the new value

Image

## Solution

Fix related hook

### PR DESCRIPTION
**Pull request by tu11aa**
# Fix: Fast Reload not working on testnet mode

Fixes #493

## Types of change

- [ ] Feature
- [X] Bug
- [X] Enhancement

## Changes:
- Reload states after transaction is complete
- Correct notification flow

## Critical Changes:
**useTransactor behavior:**
  - Center sending transaction logic into this hook, no need to create other `useSendTransaction` and `useTransactionReceip`t hooks seperately
  - Automatically handle transaction status and push correct notification
  - return `writeTransaction`, `transactionReceiptInstance`, `sendTransactionInstance` instead of only writeTransaction

**writeTransaction behavior:**
  - `writeTransaction` now only accept Call[] parameter
  - `writeTransaction` can take optional parameter `withSendTransaction = false` to use manually send transaction with fallback, otherwise it will use sendTransaction hook as default

### CODE REVIEW

**Comment by gianalarcon** [comment]
LGTM!
Tested on devnet and sepolia, both of them work well 
@tu11aa pls provide a much better description regarding to to the refactors you applied

File: packages/nextjs/hooks/scaffold-stark/useTransactor.tsx [hunk 1]
```diff
@@ -71,93 +121,34 @@ export const useTransactor = (
...
-
-          transactionHash = (await walletClient.execute(tx, txOptions))
-            .transaction_hash;
-        } catch (feeEstimationError) {
-          console.warn(
-            "Fee estimation failed, using fallback values:",
-            feeEstimationError,
-          );
-
-          // Fallback to safe default values if estimation fails
```
Comment (gianalarcon) [inline packages/nextjs/hooks/scaffold-stark/useTransactor.tsx:107]: I think we still need this fallback related to fee estamation fails related to tx v3, starknet.js v7

Comment (tu11aa) [reply packages/nextjs/hooks/scaffold-stark/useTransactor.tsx:107]: I will add a option to use this fallback

File: packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts [hunk 2]
```diff
@@ -69,20 +67,13 @@ export const useScaffoldWriteContract = <
...
-        } catch (e: any) {
-          throw e;
-        } finally {
-          // setIsMining(false);
-        }
-      } else {
-        notification.error("Contract writer error. Try again.");
-        return;
+      try {
+        // setIsMining(true);
```
Comment (metalboyrick) [inline packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts:71]: lets clean these comments up ? cc @gianalarcon to confirm whether this is still needed

File: packages/nextjs/hooks/scaffold-stark/useTransactor.tsx [hunk 3]
```diff
@@ -7,12 +7,26 @@ import {
...
+  UseSendTransactionResult,
+  useTransactionReceipt,
+  UseTransactionReceiptResult,
+} from "@starknet-react/core";
 
 type TransactionFunc = (
-  tx: () => Promise<InvokeFunctionResponse> | Promise<string>,
+  tx: Call[],
+  withSendTransaction?: boolean,
   // | SendTransactionParameters,
```
Comment (metalboyrick) [inline packages/nextjs/hooks/scaffold-stark/useTransactor.tsx:21]: this as well @gianalarcon

**Review by metalboyrick — CHANGES_REQUESTED** [review]
minor comments from me, tested functionality and works fine!

File: packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts (hunk 2 above)
Comment (gianalarcon) [reply packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts:71]: yes, we can clean up these comments

File: packages/nextjs/hooks/scaffold-stark/useTransactor.tsx (hunk 3 above)
Comment (gianalarcon) [reply packages/nextjs/hooks/scaffold-stark/useTransactor.tsx:21]: yes, we can clean up these comments

**Review by gianalarcon — COMMENTED** [review]
Just need to cleanup few comments @tu11aa 
then we ready to merge, right? @metalboyrick
