### PR TITLE
Fix conflict flag deploy --no-reset

### LINKED ISSUE #454: Bug: Inconsistency in `yarn deploy` help text and Actual Behavior
## Description
There's an inconsistency between the help text for `yarn deploy` and the actual supported options. The help text shows `--no-reset` as an option, but the actual CLI implementation expects `--reset`.

## Steps to Reproduce
1. Observe this framework supports commands as `yarn deploy` and [`yarn deploy:no-reset`](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/9ebef71d6c6ec647c4a73ae41d541b1e50fd463f/package.json#L16)
2. Now run `yarn deploy --help` 
3. When looking at the showed CLI options:  

Image

## Expected Behavior 
1. The CLI options should not show `--reset` flag and should support `--no-reset` as shown in the actual commands supported by the framework.

## Actual Behavior
The framwork codebase shows `--no-reset` option, but the CLI implementation expects `--reset`.

## Proposed Solution
**Update the help text to remove `--no-reset` and replace it with the correct `--reset` option.**

### PR DESCRIPTION
**Pull request by Buuh2511**
# Fix conflict flag deploy --no-reset

Fixes #454 

## Types of change

- [ ] Feature
- [x] Bug
- [ ] Enhancement

### CODE REVIEW

**Review by Nadai2010 — APPROVED** [review]
Hi @Buuh2511, good work! 

Both the flags, such as `yarn deploy:no-reset` or `yarn deploy --no-reset`, work fine for me.

@metalboyrick , can you check it?

File: packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts [hunk 1]
```diff
@@ -15,31 +15,40 @@ function main() {
       type: "string",
       choices: ["devnet", "sepolia", "mainnet"],
       default: "devnet",
+      description: "Specify the network to deploy to",
     })
     .option("reset", {
       type: "boolean",
-      description: "Do not reset deployments (keep existing deployments)",
+      description: "Reset deployments (remove existing deployments)",
```
Comment (gianalarcon) [inline packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts:22]: I dont think this description is 100% accurate, 
What `reset` will do is overwrite the "devnet_latest" (or sepolia_latest) file 
In case before we did `yarn deploy:no-reset`, we still will keep those previous generated files after `reset`.

Comment (Buuh2511) [reply packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts]: i have fixed the desc in new commit sir

**Review by gianalarcon — APPROVED** [review]

**Review by metalboyrick — APPROVED** [review]
