### PR TITLE
chore: fixed bug for untyped enum

### LINKED ISSUE #538: [Bug] Improve handling of untyped enums
## Issue Overview

On this [branch](https://github.com/Scaffold-Stark/scaffold-stark-2/tree/untyped-enum)
We introduced a untyped enum

```cairo
/// Represents the possible states of a Multisig transaction.
#[derive(Copy, Drop, Serde, starknet::Store, PartialEq, Debug)]
pub enum TransactionState {
    #[default]
    NotFound,
    Pending,
    Confirmed,
    Executed,
}
```

When writing with enums which are not typed, `debug-ui` will require us to choose a variant/option and input something into the input-box. Check below

Image

## Proposed Solutions or Ideas

The ABI genereted for this enum looks something like this :
https://github.com/Scaffold-Stark/scaffold-stark-2/blob/d71930f7556a7f6f1bdea0e13c301a4e6966d7e7/packages/nextjs/contracts/deployedContracts.ts#L78-L99

The `Debud contracts` should handle this kind of enums properly, it should work without having to input anything on the input-box. As long a we choose a variant/option it should be ok to `send` 

In case it actually needs an input, like `()` input, it should be handled internally when creating the Enum on the react hook.

### PR DESCRIPTION
**Pull request by Imdavyking**
# Improve handling of untyped enums

Fixes #538

## Types of change

- [ ] Feature
- [x] Bug
- [ ] Enhancement

Closes #538

### CODE REVIEW

**Comment by gianalarcon** [comment]
Looks good to me. Please apply `yarn format`

**Comment by Imdavyking** [comment]
thank you
ran yarn format

File: packages/nextjs/app/debug/_components/contract/ContractInput.tsx [hunk 1]
```diff
@@ -98,6 +98,9 @@ export const ContractInput = ({
       !isCairoResult(paramType.type) &&
       !isCairoOption(paramType.type)
     ) {
+      if (paramType.type == "()") {
```
Comment (metalboyrick) [inline packages/nextjs/app/debug/_components/contract/ContractInput.tsx:101]: can we abstract this check into an utility function? we can call it `isCairoVoid`. so that we have convention consistency, similar to line 99.

**Review by metalboyrick — CHANGES_REQUESTED** [review]
Thanks for the PR! Functionality works good!

Some minor comments, and also do not forget to update the test cases if there are any!

**Comment by Imdavyking** [comment]
Done that and wrote tests

**Review by gianalarcon — APPROVED** [review]

**Comment by gianalarcon** [comment]
Thank you so much for your contribution and joining ODHack 14 @Imdavyking
