### PR TITLE
fix: useScaffoldContract write bug with external wallets #252

### LINKED ISSUE #252: [BUG] useScaffoldContract write bug with external wallets
## Issue Overview

Current `useScaffoldContract` contract can only support read operations but not write with extension wallets. We want full functionality of the `Contract` instance of `starknet.js`

## Proposed Solutions or Ideas

- Override `call` function of the contract instance with `parseResponse` as `false` (note that this only works on Bravoos). Argent method TBD

### PR DESCRIPTION
**Pull request by ShantelPeters**
# useScaffoldContract write bug with external wallets #252

Fixes #252 

## Types of change

- [ ] Feature
- [x] Bug
- [x] Enhancement

### CODE REVIEW

**Comment by Nadai2010** [comment]
Hi @ShantelPeters , run the `yarn format` command to correct the format with the correct rules and check that the github CI is green.

**Comment by ShantelPeters** [comment]
Hi, ran
`$ yarn format`
and
```
$ yarn format:check
Checking formatting...
All matched files use Prettier code style!
Checking formatting...
All matched files use Prettier code style!
```
and found no problems.

File: packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts [hunk 1]
```diff
@@ -10,15 +11,29 @@ export const useScaffoldContract = <TContractName extends ContractName>({
...
+    contractInstance.call = async (method: string, ...args: any[]) => {
+      try {
+        return await originalCall(method, ...args, { parseResponse: false });
+      } catch (error) {
+        return originalCall(method, ...args);
+      }
+    };
+
+    return contractInstance;
+  }, [deployedContractData, publicClient]);
```
Comment (iossocket) [inline packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts:36]: please add unit tests to cover the logic inside of `useMemo`, thanks

**Comment by ShantelPeters** [comment]
Screenshot from 2024-12-17 06-39-14

File: packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts [hunk 2]
```diff
@@ -10,18 +11,32 @@ export const useScaffoldContract = <TContractName extends ContractName>({
...
-      [...deployedContractData.abi],
+
+  const contract = useMemo(() => {
+    if (!deployedContractData) return undefined;
+
+    const contractInstance = new Contract(
+      deployedContractData.abi as Abi,
       deployedContractData.address,
-      publicClient,
+      publicClient
```
Comment (metalboyrick) [inline packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts]: should involve `WalletClient` or `Account` instance since `publicClient` cannot sign messages.

**Review by metalboyrick — CHANGES_REQUESTED** [review]
I think this PR has not address the issue correctly ser. The intention is to make the contract instance be able to write.

i tried testing it with the following implementation:

image

and got this error:

image

I noticed that you have not included wallet client when creating the instance. Public Client cannot do any write signature since they don't sign anything.

File: packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts [hunk 3]
```diff
@@ -13,14 +13,15 @@ export const useScaffoldContract = <TContractName extends ContractName>({
...
 
   const contract = useMemo(() => {
-    if (!deployedContractData) return undefined;
+    if (!deployedContractData || !account) return undefined;
 
     const contractInstance = new Contract(
       deployedContractData.abi as Abi,
       deployedContractData.address,
-      publicClient,
+      account,
```
Comment (metalboyrick) [inline packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts:24]: use `publicClient` as fallback value

**Review by metalboyrick — CHANGES_REQUESTED** [review]
please also make sure that writing with the hooks work, the most important thing is it woks.

**Review by metalboyrick — CHANGES_REQUESTED** [review]
GM Ser, unfortunately the issue from before still persists.

Also, I tried using another implementation and got the following error

Implementation: 
image


Error:
image

I think it would be helpful to refer to the previous issue on this matter: #243

File: packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts [hunk 4]
```diff
@@ -93,13 +116,13 @@ describe("useScaffoldContract", () => {
...
+  //   renderHook(() => useScaffoldContract({ contractName }));
 
-    expect(MockedRpcProvider).toHaveBeenCalledWith({
-      nodeUrl: "https://mock-rpc-url",
-    });
-  });
+  //   expect(MockedRpcProvider).toHaveBeenCalledWith({
+  //     nodeUrl: "https://mock-rpc-url",
+  //   });
+  // });
```
Comment (metalboyrick) [inline packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts:125]: lets clean up the comments

**Review by metalboyrick — CHANGES_REQUESTED** [review]
minor comments left, nice work on fixing the write issue! works on my end. 

image

File: packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts (hunk 4 above)
Comment (ShantelPeters) [reply packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts]: Fixed, ser.

**Review by metalboyrick — APPROVED** [review]
