### PR TITLE
Fix display enum

### LINKED ISSUE #464: Bug: Scaffold Stark UI Doesn't Displays Enum Values
## Issue Summary
The current version of Scaffold Stark doesn't properly support showing `Enum` values. This issue is evident in the UI representation of span-typed variables.

## Observed Behavior
Based on branch [test/enum](https://github.com/Scaffold-Stark/scaffold-stark-2/compare/test/enum?expand=1)
1. Call `transaction_state`, it should display a hardcoded enum value (based on the smart contract), but Debug contracts UI breaks 

## How to reproduce
1. Run scaffold stark (yarn chain -> yarn deploy -> connect with burner wallet)
2. Input any number value on `transaction_state`
Image
3. UI breaks 
Image

## Proposed solution
Check how Scaffold Stark is parsing the enum values and show the expected result on UI

### PR DESCRIPTION
**Pull request by Buuh2511**
# Fix display enum

Fixes #464 

## Types of change

- [ ] Feature
- [x] Bug
- [ ] Enhancement

### CODE REVIEW

**Review by Nadai2010 — APPROVED** [review]
Good Job @Buuh2511, Now the transaction_state returns "Not Found," I think that's what's expected, so it's fine by me.

@gianalarcon , @metalboyrick, check for the merged please.

imagen

**Comment by gianalarcon** [comment]
At the end, This PR will get merged into `main` branch, `test/enum` is just for testing locally

**Comment by gianalarcon** [comment]
Hi @Buuh2511 Still need to handle point 2. pls

> 1. At the end, This PR will get merged into `main` branch, `test/enum` is just for testing locally
> 2. We have a folder with to test data types. Have a look there and update or create test for enums
> 3. Handling enum is quite complex, it has many variants, but I think for now the way you are solving is ok

File: packages/nextjs/contracts/deployedContracts.ts
Comment (metalboyrick) [inline packages/nextjs/contracts/deployedContracts.ts:1]: please revert, do not commit this file

**Review by metalboyrick — CHANGES_REQUESTED** [review]
same as gian comments! also please make ci green

File: packages/nextjs/contracts/deployedContracts.ts
Comment (Buuh2511) [reply packages/nextjs/contracts/deployedContracts.ts:1]: yes sir

File: packages/nextjs/app/debug/_components/contract/__test__/mock/mockABI.ts [hunk 1]
```diff
@@ -515,4 +531,26 @@ export const abi: any = [
       },
     ],
   },
+  {
```
Comment (gianalarcon) [inline packages/nextjs/app/debug/_components/contract/__test__/mock/mockABI.ts:534]: this 4 variants are redundant, lets keep 1 or max 2

Comment (Buuh2511) [reply packages/nextjs/app/debug/_components/contract/__test__/mock/mockABI.ts:534]: yes sir, i made changes, just keep one for now

**Review by gianalarcon — APPROVED** [review]

**Review by metalboyrick — APPROVED** [review]
